# Generated by Django 5.0.2 on 2024-02-16 09:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_model_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ac_model_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ac_payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ac_payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_holder', to='base.position')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ac_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_price', models.IntegerField()),
                ('model_margin', models.IntegerField()),
                ('model_cash_price', models.IntegerField()),
                ('model_dealer_price', models.IntegerField()),
                ('price_since', models.DateTimeField()),
                ('model_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ac_model_brand')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ac_model_type')),
            ],
        ),
        migrations.CreateModel(
            name='Ac_warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('model_amount', models.IntegerField()),
                ('model', models.ManyToManyField(related_name='warehouse', to='base.ac_model')),
                ('warehouse_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_warehouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ac_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('model_amount', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=70)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_man', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField()),
                ('is_shipped', models.BooleanField(default=False)),
                ('shipped_at', models.DateTimeField()),
                ('returned_amount', models.IntegerField()),
                ('returned_at', models.DateTimeField()),
                ('paid_summ', models.IntegerField()),
                ('paid_at', models.DateTimeField()),
                ('paid_by_contr_summ', models.IntegerField()),
                ('paid_by_contr_at', models.DateTimeField()),
                ('contr_num', models.CharField(max_length=70)),
                ('returned_payment', models.IntegerField()),
                ('returned_payment_at', models.DateTimeField()),
                ('returned_payment_why', models.CharField(max_length=70)),
                ('manager_debt', models.IntegerField()),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
                ('model', models.ManyToManyField(related_name='apps', to='base.ac_model')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='base.ac_payment_status')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='base.ac_payment_type')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='base.ac_warehouse')),
            ],
        ),
    ]
