# Generated by Django 5.0.2 on 2024-02-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac_app',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='contr_num',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='is_shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='manager_debt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='paid_by_contr_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='paid_by_contr_summ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='paid_summ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='returned_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='returned_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='returned_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='returned_payment_why',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ac_app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
